artifact_location: file:///C:/Users/shahe/OneDrive/Desktop/University/8th Semester/MLOPS/Project/Project_MLOps/mlflow/154843507239411349
creation_time: 1747070094396
experiment_id: '154843507239411349'
last_update_time: 1747070094396
lifecycle_stage: active
name: MLOps_Experiment
